# Rules: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md
# We use tabs and do not use spaces
# Issue: https://github.com/DavidAnson/markdownlint/issues/82
MD010: false
MD013:
  line_length: 120
  heading_line_length: 40
  code_block_line_length: 600
