#!/bin/bash
declare -A checks

checks['tar']='tar --version'
checks['xargs']='xargs --version'
checks['realpath']='realpath --version'
checks['nohup']='nohup --version'
checks['nano']='nano --version'
checks['php']='php -r "(float) PHP_VERSION >= 5.5 ?: exit(1);"'
checks['php-fpm']='php-fpm -v'
checks['nginx']='nginx -v'
checks['crontab']='which crontab'

run_checks