#!/bin/bash
. $(dirname `realpath $0`)/functions.sh
declare -A checks
declare -A results

checks['tar']='tar --version'
checks['xargs']='xargs --version'
checks['realpath']='realpath --version'
checks['nohup']='nohup --version'
checks['php']='php -r "(float) PHP_VERSION >= 5.5 ?: exit(1);"'
checks['php-fpm']='php-fpm -v'
checks['nginx']='nginx -v'

run_checks
