#!/usr/bin/env bash
kc_dir=$(cd "$(dirname $0)" && pwd)

echo -e '\e[1;35mInstall kiss bash env\e[0m'
test -d $HOME/.bin || mkdir -p $_
/bin/cp -avr $kc_dir/bin/. $HOME/.bin
/bin/cp -avr $kc_dir/.kissrc $HOME/.kissrc
cat $HOME/.bashrc | grep -v '#.kissrc$' > $HOME/.bashrc.tmp
echo 'source '$HOME'/.kissrc #.kissrc' >> $HOME/.bashrc.tmp
/bin/mv $HOME/.bashrc.tmp $HOME/.bashrc
. $HOME/.kissrc
echo '...done'
