#!/usr/bin/env bash
[[ -z "$1" ]] && echo 'Enter name of project to create. Example: ./install-core app' && exit 255
[[ ! -e "$HOME/$1" ]] && echo 'Cant find project dir '$HOME'/'$1'. Use ./make-app '$1 && exit 255

core_file=$HOME/$1/app/core.php
echo '<?php' > $core_file
echo -e '\e[1;35mInstall kiss core to '$1'\e[0m'
for file in core/*; do
  echo 'Add file '$file;
  tail -n +2 $file >> $core_file
  echo >> $core_file
done
echo 'Write into '$core_file
echo '...done'
