#!/bin/bash
`dirname $0`/install-env
. ~/.kissrc
if [[ "$1" == "" ]]; then
  echo 'Enter name of project to create. Example: ./make-app app'
  exit 1
fi

project_dir=$HOME/$1
if [[ -e $project_dir ]]; then
  echo 'Project dir '$project_dir' already exist'
  exit 1
fi

# Start doing good staff
echo -e '\e[1;35mCheck software\e[0m'

if [[ "$?" != "0" ]]; then
  echo "...failed"
  exit 1
fi
echo '...done'

echo -e '\e[1;35mCopy skeleton to project dir\e[0m'
mkdir $project_dir
cp -avr skel/* $project_dir
mkdir -p $project_dir/env/{tmp,var,run,log,backup}
mkdir -p $project_dir/app/{lib,tests}
echo '...done'

echo -e '\e[1;35mConfigure etc templates\e[0m'
env_dir=$project_dir'/env'
app_dir=$project_dir'/app'
tmp_dir=$env_dir'/tmp'
var_dir=$env_dir'/var'
run_dir=$env_dir'/run'
etc_dir=$env_dir'/etc'
epoch=$(date +%s)'000'
secret_key=$(ssh_random_string 'A-Za-z0-9' 64)
# Replace global static variables for init project
cat skel/app.ini.tpl \
  | sed "s|%KISS_EPOCH%|$epoch|g" \
  | sed "s|%KISS_SECRET_KEY%|$secret_key|g" \
  > $etc_dir/app.ini.tpl
echo '...done'

echo -e '\e[1;35mInstall compiled core file to project\e[0m'
./install-core $1
echo '...done'

echo -e '\e[1;35mInitializing new application\e[0m'
kiss $1 << "EOF"
  init
EOF
echo '...done'
