#!/bin/bash
. functions.sh
if [[ "$1" == "" ]]; then
  echo 'Enter name of project to create. Example: ./make-app app'
  exit 1
fi

project_dir=$HOME/$1
if [[ -e $project_dir ]]; then
  echo 'Project dir '$project_dir' already exist'
  exit 1
fi

# Start doing good staff
echo -e '\e[1;35mCheck software\e[0m'
./check
if [[ "$?" != "0" ]]; then
  echo "...failed"
  exit 1
fi
echo '...done'

echo -e '\e[1;35mCopy skeleton to project dir\e[0m'
mkdir $project_dir
cp -r skel/* $project_dir
echo '...done'

echo -e '\e[1;35mConfigure etc\e[0m'
env_dir=$project_dir'/env'
app_dir=$project_dir'/app'
tmp_dir=$env_dir'/tmp'
var_dir=$env_dir'/var'
run_dir=$env_dir'/run'
etc_dir=$env_dir'/etc'
for file in $(ls skel/env/etc); do
  cat skel/env/etc/$file \
    | sed "s|%USER%|$USER|g" \
    | sed "s|%GROUP%|$GROUP|g" \
    | sed "s|%PROJECT_DIR%|$project_dir|g" \
    | sed "s|%URI_MAP_FILE%|$var_dir/uri_request_map.json|g" \
    | sed "s|%AUTOLOAD_MAP_FILE%|$var_dir/php_autoload_map.json|g" \
    | sed "s|%DEV_HOST%|$1.lo|g" \
    | sed "s|%VIEW_SOURCE_DIR%|$app_dir/views|g" \
    | sed "s|%VIEW_COMPILE_DIR%|$tmp_dir|g" \
    > $etc_dir/$file
done
echo '...done'

echo -e '\e[1;35mInstall compiled core file to project\e[0m'
./install-core $1
echo '...done'

echo -e '\e[1;35mPrepare tasks\e[0m'
cat skel/tasks \
  | sed "s|%PHP_INI_CONFIG%|$project_dir/env/etc/php.ini|g" \
  | sed "s|%PHP_FPM_CONFIG%|$project_dir/env/etc/php-fpm.conf|g" \
  > $project_dir/tasks
echo '...done'

echo -e '\e[1;35mInitializing new application\e[0m'
$project_dir/init
echo '...done'
