FROM dmitrykuzmenkov/php:7.1.3-fpm
MAINTAINER Dmitrii Kuzmenkov <dmitrii@kuzmenkov.me>

COPY . /src
RUN ln -fs /src/docker/containers/php/config/php.ini /etc/php/php.ini && \
  ln -fs /src/docker/containers/php/config/conf.d /etc/php/conf.d
WORKDIR /src

ENTRYPOINT ["/src/docker/containers/php/entrypoint"]
