FROM nginx:1.13.9-alpine
LABEL maintainer="Dmitrii Kuzmenkov <dmitrii@kuzmenkov.me>"

RUN mkdir /var/cache/nginx/client_temp /var/cache/nginx/fastcgi_temp \
  /var/cache/nginx/proxy_temp /var/cache/nginx/scgi_temp /var/cache/nginx/uwsgi_temp
COPY . /src
WORKDIR /src

ENTRYPOINT ["/src/docker/containers/nginx/entrypoint"]
CMD [""]
