# Only development
image: watcher
labels:
  - role=php
working_dir: /src
network_mode: bridge
restart: unless-stopped
cap_drop:
  - ALL
cap_add:
  - CHOWN
environment:
  - PHP_CONTAINER=${COMPOSE_PROJECT_NAME}.php.0
  - NGINX_CONTAINER=${COMPOSE_PROJECT_NAME}.nginx.0
volumes:
  - ${SOURCE_PATH}:/src
  - /var/run/docker.sock:/var/run/docker.sock
  - env-storage:/src/env:rw