#!/usr/bin/env bash
path="/src/app/actions /src/app/config"

compare() {
  # Command to update maps
  id=$(curl --silent -0 -H 'Content-type: application/json' --unix-socket /var/run/docker.sock -d '{"Cmd": ["bin/php-exec", "Env::init()"]}' -X POST localhost/containers/${PHP_CONTAINER}/exec | cut -d '"' -f 4)
  curl --silent -0 -H 'Content-type: application/json' --unix-socket /var/run/docker.sock -X POST -d '{"Detach": false, "Tty": false}' localhost/exec/$id/start
  curl --silent -0 -H 'Content-type: application/json' --unix-socket /var/run/docker.sock -X POST localhost/containers/${NGINX_CONTAINER}/kill?signal=HUP

}
trap exit SIGINT SIGTERM EXIT

inotifywait -r -e 'create,delete,modify,move' --monitor $path | \
  while read -r notifies; do
    echo "$notifies"
    compare
  done
