#!/usr/bin/env bash
set -e
if [[ -z "$1" ]]; then
  echo 'Usage '$0' [path-to-project]'
  exit 1
fi

if [[ ! -d "$1" ]]; then
  echo "Path '$1' does not exist or its not a directory"
  exit 1
fi

PROJECT_PATH=$(cd `dirname $1` && pwd)
PROJECT_NAME=${PROJECT_PATH##*\/}
ADDON_PATH=$(cd `dirname $0` && pwd)
cp -r "$ADDON_PATH/skel/"* "$1/"

sed  -i.bak "/  ->prepend('_head')/d" "$1/app/main.php" && rm -f "$_.bak"
sed  -i.bak "/  ->append('_foot');/d" "$1/app/main.php" && rm -f "$_.bak"
sed -E -i.bak 's/^(\$View = App::process\(\))$/\1\;/g' "$1/app/main.php" && rm -f "$_.bak"
