#!/bin/bash
host_file=$PROJECT_DIR/hosts
if [[ ! -f $host_file ]]; then
  echo 'Create hosts "'$host_file'" file with hostnames to deploy on'
  exit 1
fi
servers=$(cat $host_file)

if [[ -z $servers ]]; then
  echo 'There are no servers for deploy in hosts file'
  exit 1
fi

# Deploy on each server
for server in $servers; do
  (
  echo 'Deploying on server '$server
  
  scp $HOME/.kissrc prod@$server:/home/prod
  ssh -T prod@$server <<"EOF"
    /bin/cat $HOME/.bashrc | /bin/grep -v '#.kissrc$' > $HOME/.bashrc.tmp
    echo "source $HOME/.kissrc #.kissrc" >> $HOME/.bashrc.tmp
    /bin/mv $HOME/.bashrc.tmp $HOME/.bashrc
    source $HOME/.bashrc
EOF

  # Check for already created folder on server
  ssh -T prod@$server '[[ ! -d /home/prod/'$PROJECT' ]]'
  if [[ $? == "0" ]]; then
    ssh -T prod@$server 'mkdir -p /home/prod/'$PROJECT'/env/{etc,log,var,run,bin,tmp,backup}'
    ssh -T prod@$server 'mkdir -p /home/prod/'$PROJECT'/app'
    rsync -aiz env/etc/ prod@$server:/home/prod/$PROJECT/env/etc
  fi
  
  # sync onlye changed files
  rsync -aiz --exclude=env* --exclude=sphinx* \
    --exclude=.git* --exclude=html/f* \
    --exclude=connect-db . prod@$server:/home/prod/$PROJECT

  # Compile PROJECT on server
  ssh -T prod@$server <<EOF
    kiss $PROJECT
    init
    [[ \$(/bin/ls \$TMP_DIR) ]] && /bin/rm \$TMP_DIR/*
EOF
  # All is done
  echo 'Deployed on server '$server
  ) > $TMP_DIR/deploy.$server 2>&1 &
done
wait

# Display result of jobs
for file in $(ls $TMP_DIR/deploy.*); do
  cat $file
  rm $file
done