#!/bin/bash
APP_DIR=$(dirname `realpath $0`)
echo 'Initialization started'
echo '+Compile project'
$APP_DIR/php-exec 'App::compile()'
echo '...done'
echo '+Reloading services'
sudo /etc/init.d/nginx reload
echo '...done'
