#!/bin/bash
echo 'Initialization started'
echo '+Configure and compile project'
task add "php-fpm -c $CONFIG_DIR/php.ini -y $CONFIG_DIR/php-fpm.conf -F #php-fpm"
php-exec 'App::compile()'
echo '...done'
echo '+Reloading services'
[[ -x /etc/init.d/nginx ]] && sudo /etc/init.d/nginx reload || sudo /usr/bin/systemctl reload nginx.service
echo '...done'
echo '+Reconfigure crontab'
crontab=$(which crontab)
$crontab -l | grep -v '#'$PROJECT'$' > $TMP_DIR/.crontab.tmp
echo '* * * * * source ~/.kissrc ; kiss '$PROJECT' ; run ; #'$PROJECT >> $TMP_DIR/.crontab.tmp
$crontab $TMP_DIR/.crontab.tmp
/bin/rm $TMP_DIR/.crontab.tmp
echo '...done'
