#!/bin/bash
trap "pgrep -P $$ | while read process; do pkill -SIGTERM -P \$process; kill \$process; done; pgrep -f $(dirname `realpath $0`) | xargs kill; wait; exit 0" SIGINT SIGTERM
while true; do
  readarray TASKS < $(dirname $0)/tasks
  for i in "${!TASKS[@]}"; do
    if [[ ${PIDS[$i]+isset} && $(ps -p ${PIDS[$i]} -o pid | sed 1d) ]]; then
      continue
    fi
    ( ${TASKS[$i]% \#*} ) & PIDS[$i]=$!
  done
  sleep 1
done
