#!/bin/bash
if [[ -z $2 ]];  then
  echo 'Usage: '$0' add|remove command|#id'
  exit 1
fi

tasks_file=$PROJECT_DIR/tasks
id=${2##*\#}

cat $tasks_file | grep -v \#$id$ | sort -V > $tasks_file.tmp
case $1 in
  add)
    echo $2 >> $tasks_file.tmp
    ;;
  remove)
    
    ;;
  *)
    echo 'There is no such action: '$1
    exit 1
    ;;
esac
/bin/mv $tasks_file.tmp $tasks_file