#!/bin/bash
if [[ -z $1 ]];  then
  echo 'Usage: '$0' add|remove|edit|list|print [command|#id]'
  exit 1
fi

tasks_file=$PROJECT_DIR/tasks
id=${2##*\#}

cat $tasks_file | grep -v \#$id$ | sort -V > $tasks_file.tmp
case $1 in
  add)
    if [[ -z $2 ]]; then
      echo 'Specify command to add. Example: task add memcached'
      /bin/rm $tasks_file.tmp
      exit 1
    fi
    echo $2 >> $tasks_file.tmp
    ;;
  remove)
    if [[ -z $2 ]]; then
      echo 'Specify command to add. Example: task add memcached'
      /bin/rm $tasks_file.tmp
      exit 1
    fi
    ;;
  edit)
    nano $tasks_file
    ;;
  list|print)
    cat $tasks_file
    ;;
  *)
    echo 'There is no such action: '$1
    /bin/rm $tasks_file.tmp
    exit 1
    ;;
esac
/bin/mv $tasks_file.tmp $tasks_file