#!/bin/bash
sha=0
update_sha() {
  sha=`ls -lR --time-style=full-iso $(pwd)/{app,env/etc} | sha1sum`
}
update_sha
previous_sha=$sha
build() {
  echo -en " rebuilding..."
  $(pwd)'/init' > /dev/null 2>&1
  echo -en "\n--> resumed watching."
}
compare() {
  update_sha
  if [[ $sha != $previous_sha ]] ; then
    echo -n "change detected,"
    build
    previous_sha=$sha
  else
    echo -n .
  fi
}
trap build SIGINT
trap exit SIGQUIT

echo -e  "--> Press Ctrl+C to force build, Ctrl+\\ to exit."
echo -en "--> watching."
while true; do
  compare
  sleep 1
done
