#!/usr/bin/env /src/bin/php-exec-one
<?php
$action_map = Env::load(config('common.action_map_file'));
$setups = [
  ['prepend' => '_head', 'append' => '_head']
];

foreach ($setups as $setup) {
  foreach (config('common.languages') as $language) {
    foreach ($action_map as $action => $file) {
      View::create($action)
        ->configure(['source_dir' => config('view.source_dir') . '/' . $language])
        ->prepend($setup['prepend'])
        ->append($setup['append'])
        ->render(true)
      ;
    }
  }
}

