FROM nginx:1.26.0-alpine
LABEL maintainer="Muvon Un Limited <hello@muvon.io>"

RUN mkdir /var/cache/nginx/client_temp /var/cache/nginx/fastcgi_temp \
  /var/cache/nginx/proxy_temp /var/cache/nginx/scgi_temp /var/cache/nginx/uwsgi_temp
COPY . /src
WORKDIR /src

ENTRYPOINT ["/src/docker/containers/nginx/entrypoint"]
CMD [""]
