FROM muvon/php:8.1.9
LABEL maintainer="Muvon Co. Ltd <contact@muvon.io>"

RUN apk add --update bash openssl && \
  rm -fr /var/cache/apk/* && \
  rm -fr /tmp/*
RUN php-ext add msgpack yaml openswoole

COPY . /src
RUN ln -fs /src/docker/containers/php/config/php.ini /etc/php/php.ini && \
  ln -fs /src/docker/containers/php/config/conf.d /etc/php/conf.d
WORKDIR /src

ENTRYPOINT ["/src/docker/containers/php/entrypoint"]
