FROM node:18.7.0-alpine3.15
LABEL maintainer="Muvon Co. Ltd <contact@muvon.io>"

RUN mkdir -p /src
COPY package.json /src
ENV BUILD_DEPS="build-base python3"
RUN apk add $BUILD_DEPS && \
  cd /src && yarn install && yarn cache clean && \
  apk del $BUILD_DEPS
COPY . /src

WORKDIR /src
