FROM node:14.7.0-alpine3.12
LABEL maintainer="Muvon Co. Ltd <contact@muvon.io>"

RUN mkdir /src

COPY package.json /src/package.json
RUN cd /src && yarn install && yarn cache clean

COPY app/client /src/app/client
COPY docker /src/docker
WORKDIR /src
