image: db
labels:
  - role=db
environment:
  - MYSQL_DATABASE=${DB_NAME}
  - MYSQL_USER=${DB_USER}
  - MYSQL_PASSWORD=${DB_PASSWORD}
  - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
volumes:
  - db-storage:/var/lib/mysql:rw
